---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/sob/micro-ops.git
  syncPolicy:
    automated: {}
    syncOperations:
      - CreateNamespace=true
